name: Update Latest Release


on:
  push:
    branches:
      - main

jobs:
  update-latest-release:
    runs-on: ubuntu-latest
    

    permissions:
      contents: write

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Nén và Ghi đè file Zip vào Release mới nhất
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |

          LATEST_TAG=$(gh release view --json tagName -q .tagName || echo "")
          
          if [ -z "$LATEST_TAG" ]; then
            echo "Chưa có bản Release nào để cập nhật. Vui lòng tạo Release trước!"
            exit 1
          fi
          
          echo "Đã tìm thấy bản Release mới nhất: $LATEST_TAG"
          

          ZIP_NAME="focus-pro-${LATEST_TAG}.zip"
          

          cd focus-pro
          zip -r "../${ZIP_NAME}" ./*
          cd ..
          

          gh release upload "$LATEST_TAG" "$ZIP_NAME" --clobber
